name: Rust

on:
  push:
    branches: [ "main", "ironlight" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-unbuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: cargo build --verbose

  build-mac-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: cargo build --verbose
